#JASYPT_ENCRYPTOR_PASS:
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: ${JASYPT_ENCRYPTOR_PASS}

server:
  port: 20001

proxy:
  enabled: false
  proxy-host: xxx.proxy.host
  proxy-port: 3128

spring:
  application:
    name: aquick-poc-mpt
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop #create, create-drop, update, validate, none
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    com.poc.mpt: DEBUG

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs